cookie:
      httpOnly: true
      secure: false
      time: 1

server:
    host: '0.0.0.0'
    port: 8080

disauth:
      id: 'xxxxxxxxxxxxxxxxxxxx'
      secret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      callback: 'http://xxx.xxx.xxx.xxx:8080/login/after'
      guild_id: 'xxxxxxxxxxxxxxxxxxxx'
      roleid: 'xxxxxxxxxxxxxxxxxxxx'

proxy:
      proxy_pass: 'http://xxx.xxx.xxx.xxx:8001'

redis:
      use: false
      server:
            host: 127.0.0.1
            port: 6379
            password: 'password'
